Repository calumtomeny/quiz-master, pull requests merged in 2021-01, with the labels that each got.

#112 Reduced the minWidth value for the final standings table
  quizmaster-client-app/src/components/QuizHosting/QuizStandings.tsx
Labels: bug

#114 Changed the logic for displaying the question input and table
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
Labels: enhancement, polishing

#125 Stop participant's connection from reconnecting
  quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Labels: bug

#127 Added conditional rendering to autoFocus prop
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
Labels: bug, minor

#128 feat(webapp): Reduced default answer time to 45 seconds
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
  quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Labels: enhancement

#130 test(api): Fixed API tests
  QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
  QuizMaster.Api/Postman Tests/Staging QuizMaster.postman_environment.json
Labels: testing

#131 Feature/improved question transitions
  QuizMaster.Api/Postman Tests/Quiz Master API Tests.postman_collection.json
  QuizMaster.Application/QuizMasterMessage.cs
  QuizMaster.Domain/QuizState.cs
  quizmaster-client-app/src/components/Common/QuizMasterMessage.ts
  quizmaster-client-app/src/components/Common/QuizState.ts
  quizmaster-client-app/src/components/QuizHosting/QuestionMarker.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizWizard.tsx
  quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Labels: enhancement

#133 Changed styling for the Q&A form and Material Table
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
Labels: enhancement, polishing

#143 Added FAQ to About Modal
  quizmaster-client-app/src/components/Common/AboutModal.tsx
Labels: enhancement

#149 Feature/question answer edit validation
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionCreator.tsx
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/QuestionInitialiser.tsx
  quizmaster-client-app/src/components/QuizHosting/QuestionCreator/TableFieldEditor.tsx
Labels: bug, polishing

#156 feat(webapp): Participant name must be unique in quiz
  QuizMaster.Application/Contestants/Create.cs
  quizmaster-client-app/src/components/QuizParticipating/QuizJoiner.tsx
Labels: bug, enhancement
