Repository calumtomeny/quiz-master, pull requests merged in 2021-03, with the labels that each got.

#166 feat(webapp): Changed home page background image and og-image to match
  quizmaster-client-app/public/og-image.jpg
  quizmaster-client-app/src/components/HomePage/HomePage.tsx
  quizmaster-client-app/src/components/HomePage/coffee-and-laptop.jpg
  quizmaster-client-app/src/components/HomePage/coffee-on-table.jpg
  quizmaster-client-app/src/components/HomePage/girl_with_coffee.jpeg
Labels: minor

#167 feat(webapp): Reduced default response time to 20 seconds and removed autofocus from responder
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
  quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Labels: bug

#170 feat(webapp): added in logic to render fragment when quiz starts
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Labels: bug, minor

#172 Answer marking switch: incorrect flash fix
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Labels: bug, major

#174 Calculate Score button appearing before start of first question fix
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Labels: bug, minor

#180 fix(webapp): added await on update DB for quiz end to fix race condition
  quizmaster-client-app/src/components/QuizHosting/QuizHoster.tsx
Labels: bug
