Repository calumtomeny/quiz-master, pull requests merged in 2021-05, with the labels that each got.

#193 Minor compiler warnings fix
  quizmaster-client-app/src/components/Common/QuizStandings.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizPlaying/QuizHoster.tsx
  quizmaster-client-app/src/components/QuizParticipating/ParticipantLobby.tsx
Labels: bug, minor

#189 Feature/drag and drop table
  quizmaster-client-app/package-lock.json
  quizmaster-client-app/package.json
  quizmaster-client-app/src/app/layout/Layout.tsx
  quizmaster-client-app/src/components/Common/QuizQuestion.ts
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionCreator.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionDisplay.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionInitialiser.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionReducer.ts
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/Answer.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DefaultIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DeleteIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DragIcon.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/EditIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/ModificationIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/Question.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizPlaying/QuizHoster.tsx
Labels: enhancement, minor

#195 Feature/drag and drop table
  quizmaster-client-app/src/components/Common/QuizQuestionDisplay.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionCreator.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuestionDisplay.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/Answer.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DefaultIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DeleteIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/DragIcon.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/EditIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/ModificationIcons.tsx
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuestionCreator/QuizQuestion/Question.tsx
  quizmaster-client-app/src/components/QuizParticipating/QuestionResponder.tsx
Labels: bug

#191 Put the Quiz Master url in it's own element
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuizWizard.tsx
Labels: bug, minor

#201 fix(webapp): Fixed validation of integer values for answer time
  quizmaster-client-app/src/components/QuizHosting/QuizCreating/QuizOptions.tsx
Labels: bug
